#!/usr/bin/env python3
"""Scan a release tree and, optionally, Git history for unwanted residue."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess
import sys


TERMS = (
    "ignore previous",
    "system prompt",
    "chain of thought",
    "chatgpt",
    "claude",
    "copilot",
    "as an ai",
    "generated by",
    "placeholder",
    "lorem ipsum",
    "todo",
    "fixme",
    "your_api_key",
    "api_key",
)

# Bare words such as "token" and "secret" are common in parsers, security
# documentation, and the scanner's own fixtures.  Flag credential-like values
# and well-known key prefixes instead of treating ordinary prose as leakage.
SENSITIVE_PATTERNS = (
    re.compile(r"\b(?:access[_ -]?token|auth[_ -]?token|client[_ -]?secret|password)\s*[:=]\s*['\"][^'$<{][^'\"]{7,}['\"]", re.I),
    re.compile(r"\b(?:gh[opusr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})\b"),
    re.compile(r"\b(?:sk-[A-Za-z0-9_-]{20,}|AKIA[0-9A-Z]{16})\b"),
)

# Exact, non-secret strings required by checked-in infrastructure.
SAFE_LINES = {
    "id-token: write",
}

# These exact values are the canonical final-film residue detector itself.
# The produced film, captions, resolved manifest, and metadata are still
# scanned; only the authored detector declaration is exempt.
SAFE_PATH_LINES = {
    "video/film.yaml": {
        "- todo",
        "- fixme",
        "- placeholder",
    },
}

SKIP_DIRECTORIES = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "tmp",
    "venv",
}
SELF = Path("tools/scan_release.py")
MAX_TEXT_BYTES = 5 * 1024 * 1024


def scan_bytes(label: str, content: bytes) -> list[str]:
    if b"\0" in content[:8192]:
        return []
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        return []
    findings = []
    path_safe_lines: set[str] = set()
    for suffix, values in SAFE_PATH_LINES.items():
        if label == suffix or label.endswith(f":{suffix}"):
            path_safe_lines.update(values)
    for line_number, line in enumerate(text.splitlines(), 1):
        lowered = line.casefold()
        if lowered.strip() in SAFE_LINES or lowered.strip() in path_safe_lines:
            continue
        matched = sorted({term for term in TERMS if term in lowered})
        matched.extend(
            "credential-like value" for pattern in SENSITIVE_PATTERNS if pattern.search(line)
        )
        if matched:
            findings.append(f"{label}:{line_number}: {', '.join(sorted(set(matched)))}")
    return findings


def working_tree_files(root: Path):
    for path in root.rglob("*"):
        if path.is_symlink() or not path.is_file():
            continue
        relative = path.relative_to(root)
        if relative == SELF or any(part in SKIP_DIRECTORIES for part in relative.parts):
            continue
        try:
            if path.stat().st_size <= MAX_TEXT_BYTES:
                yield relative, path.read_bytes()
        except OSError as exc:
            print(f"warning: cannot read {relative}: {exc}", file=sys.stderr)


def git(root: Path, *args: str) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def history_files(root: Path):
    revisions = git(root, "rev-list", "--all")
    if revisions.returncode != 0:
        return
    for revision in revisions.stdout.decode().splitlines():
        names = git(root, "ls-tree", "-r", "--name-only", revision)
        if names.returncode != 0:
            continue
        for name in names.stdout.decode(errors="replace").splitlines():
            relative = Path(name)
            if relative == SELF or any(part in SKIP_DIRECTORIES for part in relative.parts):
                continue
            blob = git(root, "show", f"{revision}:{name}")
            if blob.returncode == 0 and len(blob.stdout) <= MAX_TEXT_BYTES:
                yield f"git:{revision[:12]}:{name}", blob.stdout


def commit_messages(root: Path):
    messages = git(root, "log", "--format=%H %B")
    if messages.returncode == 0:
        yield "git:commit-messages", messages.stdout


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", type=Path, default=Path.cwd())
    parser.add_argument("--history", action="store_true", help="also inspect every reachable Git blob")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 2

    if args.history and git(root, "rev-parse", "--verify", "HEAD").returncode != 0:
        print("error: --history requires at least one Git commit", file=sys.stderr)
        return 2

    findings = []
    for relative, content in working_tree_files(root):
        findings.extend(scan_bytes(str(relative), content))
    if args.history:
        for label, content in history_files(root):
            findings.extend(scan_bytes(label, content))
        for label, content in commit_messages(root):
            findings.extend(scan_bytes(label, content))

    if findings:
        print("release scan found suspicious text:", file=sys.stderr)
        for finding in findings:
            print(f"  {finding}", file=sys.stderr)
        return 1
    print("release scan passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
